name: CI Checks

# Trigger the workflow only on pushes to the main branch
on:
  push:
    branches:
      - main

env:
  NODE_VERSION: "20"

jobs:
  # Install dependencies once and cache them
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js and cache pnpm dependencies
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm" # setup-node handle caching based on pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

  lint:
    name: Run Biome Lint
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js and cache pnpm dependencies
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies (from cache)
        run: pnpm install --frozen-lockfile

      - name: Run Biome Lint
        run: pnpm biome lint ./src

  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js and cache pnpm dependencies
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies (from cache)
        run: pnpm install --frozen-lockfile

      - name: Check Formatting
        run: pnpm format

  # test:
  #   name: Run Tests
  #   runs-on: ubuntu-latest
  #   needs: install
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up pnpm
  #       uses: pnpm/action-setup@v4

  #     - name: Set up Node.js and cache pnpm dependencies
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ env.NODE_VERSION }}
  #         cache: "pnpm"

  #     - name: Install dependencies (from cache)
  #       run: pnpm install --frozen-lockfile

  #     - name: Run tests
  #       run: pnpm test
